# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_analyse.ui'
#
# Created: Wed Nov 14 16:22:37 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_interface_analyse(object):
    def setupUi(self, interface_analyse):
        interface_analyse.setObjectName(_fromUtf8("interface_analyse"))
        interface_analyse.resize(534, 599)
        interface_analyse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_analyse.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(interface_analyse)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtGui.QComboBox(interface_analyse)
        self.cb_connexion.setObjectName(_fromUtf8("cb_connexion"))
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtGui.QPushButton(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName(_fromUtf8("pb_dbConnect"))
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtGui.QGroupBox(interface_analyse)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtGui.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName(_fromUtf8("cb_schema_desti"))
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName(_fromUtf8("le_table_desti"))
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(interface_analyse)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cb_schema = QtGui.QComboBox(self.groupBox_3)
        self.cb_schema.setObjectName(_fromUtf8("cb_schema"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_schema)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cb_table = QtGui.QComboBox(self.groupBox_3)
        self.cb_table.setObjectName(_fromUtf8("cb_table"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cb_table)
        self.le_annee = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_annee.sizePolicy().hasHeightForWidth())
        self.le_annee.setSizePolicy(sizePolicy)
        self.le_annee.setObjectName(_fromUtf8("le_annee"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_annee)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.scrollArea = QtGui.QScrollArea(interface_analyse)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 497, 256))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 2, 1, 1, 1)
        self.cb_geobati = QtGui.QComboBox(self.groupBox)
        self.cb_geobati.setObjectName(_fromUtf8("cb_geobati"))
        self.gridLayout_4.addWidget(self.cb_geobati, 2, 2, 1, 2)
        self.cb_indust = QtGui.QComboBox(self.groupBox)
        self.cb_indust.setObjectName(_fromUtf8("cb_indust"))
        self.gridLayout_4.addWidget(self.cb_indust, 4, 2, 1, 2)
        self.label_62 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_4.addWidget(self.label_62, 4, 1, 1, 1)
        self.cb_batirem = QtGui.QComboBox(self.groupBox)
        self.cb_batirem.setObjectName(_fromUtf8("cb_batirem"))
        self.gridLayout_4.addWidget(self.cb_batirem, 5, 2, 1, 2)
        self.label_63 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_4.addWidget(self.label_63, 5, 1, 1, 1)
        self.cb_bati_indif = QtGui.QComboBox(self.groupBox)
        self.cb_bati_indif.setObjectName(_fromUtf8("cb_bati_indif"))
        self.gridLayout_4.addWidget(self.cb_bati_indif, 6, 2, 1, 2)
        self.label_64 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_4.addWidget(self.label_64, 6, 1, 1, 1)
        self.rb_geom = QtGui.QRadioButton(self.groupBox)
        self.rb_geom.setChecked(True)
        self.rb_geom.setObjectName(_fromUtf8("rb_geom"))
        self.buttonGroup = QtGui.QButtonGroup(interface_analyse)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rb_geom)
        self.gridLayout_4.addWidget(self.rb_geom, 8, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 8, 1, 1, 1)
        self.rb_the_geom = QtGui.QRadioButton(self.groupBox)
        self.rb_the_geom.setObjectName(_fromUtf8("rb_the_geom"))
        self.buttonGroup.addButton(self.rb_the_geom)
        self.gridLayout_4.addWidget(self.rb_the_geom, 8, 3, 1, 1)
        self.label_61 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_4.addWidget(self.label_61, 0, 1, 1, 1)
        self.cb_ff_parcelle = QtGui.QComboBox(self.groupBox)
        self.cb_ff_parcelle.setObjectName(_fromUtf8("cb_ff_parcelle"))
        self.gridLayout_4.addWidget(self.cb_ff_parcelle, 0, 2, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.pb_start = QtGui.QPushButton(interface_analyse)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtGui.QLabel(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName(_fromUtf8("lbl_etape"))
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtGui.QProgressBar(interface_analyse)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName(_fromUtf8("pb_avancement"))
        self.verticalLayout.addWidget(self.pb_avancement)

        self.retranslateUi(interface_analyse)
        QtCore.QMetaObject.connectSlotsByName(interface_analyse)

    def retranslateUi(self, interface_analyse):
        interface_analyse.setWindowTitle(_translate("interface_analyse", "Création de MOS", None))
        self.label.setText(_translate("interface_analyse", "Sélectionner la connexion à la base de donnée", None))
        self.pb_dbConnect.setText(_translate("interface_analyse", "Connecter", None))
        self.groupBox_2.setTitle(_translate("interface_analyse", "Destination", None))
        self.label_3.setText(_translate("interface_analyse", "Schéma destination", None))
        self.label_4.setText(_translate("interface_analyse", "Couche destination", None))
        self.groupBox_3.setTitle(_translate("interface_analyse", "Origine", None))
        self.label_6.setText(_translate("interface_analyse", "Schema MOS", None))
        self.label_13.setText(_translate("interface_analyse", "Couche MOS", None))
        self.label_2.setText(_translate("interface_analyse", "Année T-1", None))
        self.groupBox.setTitle(_translate("interface_analyse", "Données", None))
        self.label_12.setText(_translate("interface_analyse", "edigeo batiment T-1", None))
        self.label_62.setText(_translate("interface_analyse", "ign  bati industrie T-1", None))
        self.label_63.setText(_translate("interface_analyse", "ign bati remarquable T-1", None))
        self.label_64.setText(_translate("interface_analyse", "ign bati indiferencie T-1", None))
        self.rb_geom.setText(_translate("interface_analyse", "geom", None))
        self.label_5.setText(_translate("interface_analyse", "Champ geom BD TOPO", None))
        self.rb_the_geom.setText(_translate("interface_analyse", "the_geom", None))
        self.label_61.setText(_translate("interface_analyse", "FF pnb10_parcelle T0", None))
        self.pb_start.setText(_translate("interface_analyse", "Start", None))
        self.lbl_etape.setText(_translate("interface_analyse", "TextLabel", None))

