# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_analyse.ui'
#
# Created: Fri Nov 16 17:29:26 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_interface_analyse(object):
    def setupUi(self, interface_analyse):
        interface_analyse.setObjectName(_fromUtf8("interface_analyse"))
        interface_analyse.resize(564, 627)
        interface_analyse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_analyse.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(interface_analyse)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtGui.QComboBox(interface_analyse)
        self.cb_connexion.setObjectName(_fromUtf8("cb_connexion"))
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtGui.QPushButton(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName(_fromUtf8("pb_dbConnect"))
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtGui.QGroupBox(interface_analyse)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtGui.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName(_fromUtf8("cb_schema_desti"))
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName(_fromUtf8("le_table_desti"))
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(interface_analyse)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cb_schema = QtGui.QComboBox(self.groupBox_3)
        self.cb_schema.setObjectName(_fromUtf8("cb_schema"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_schema)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cb_table = QtGui.QComboBox(self.groupBox_3)
        self.cb_table.setObjectName(_fromUtf8("cb_table"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cb_table)
        self.le_annee = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_annee.sizePolicy().hasHeightForWidth())
        self.le_annee.setSizePolicy(sizePolicy)
        self.le_annee.setObjectName(_fromUtf8("le_annee"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_annee)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_61 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_61)
        self.cb_ff_parcelle = QtGui.QComboBox(self.groupBox)
        self.cb_ff_parcelle.setObjectName(_fromUtf8("cb_ff_parcelle"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_ff_parcelle)
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea_2 = QtGui.QScrollArea(interface_analyse)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 527, 225))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 1, 1, 1, 1)
        self.cb_geobati = QtGui.QComboBox(self.groupBox_4)
        self.cb_geobati.setObjectName(_fromUtf8("cb_geobati"))
        self.gridLayout_5.addWidget(self.cb_geobati, 1, 2, 1, 2)
        self.cb_indust = QtGui.QComboBox(self.groupBox_4)
        self.cb_indust.setObjectName(_fromUtf8("cb_indust"))
        self.gridLayout_5.addWidget(self.cb_indust, 3, 2, 1, 2)
        self.label_65 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_5.addWidget(self.label_65, 3, 1, 1, 1)
        self.cb_batirem = QtGui.QComboBox(self.groupBox_4)
        self.cb_batirem.setObjectName(_fromUtf8("cb_batirem"))
        self.gridLayout_5.addWidget(self.cb_batirem, 4, 2, 1, 2)
        self.cb_bati_indif = QtGui.QComboBox(self.groupBox_4)
        self.cb_bati_indif.setObjectName(_fromUtf8("cb_bati_indif"))
        self.gridLayout_5.addWidget(self.cb_bati_indif, 5, 2, 1, 2)
        self.label_66 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_5.addWidget(self.label_66, 4, 1, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_5.addWidget(self.label_67, 5, 1, 1, 1)
        self.rb_geom = QtGui.QRadioButton(self.groupBox_4)
        self.rb_geom.setChecked(True)
        self.rb_geom.setObjectName(_fromUtf8("rb_geom"))
        self.gridLayout_5.addWidget(self.rb_geom, 7, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 7, 1, 1, 1)
        self.rb_the_geom = QtGui.QRadioButton(self.groupBox_4)
        self.rb_the_geom.setObjectName(_fromUtf8("rb_the_geom"))
        self.gridLayout_5.addWidget(self.rb_the_geom, 7, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.pb_start = QtGui.QPushButton(interface_analyse)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtGui.QLabel(interface_analyse)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName(_fromUtf8("lbl_etape"))
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtGui.QProgressBar(interface_analyse)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName(_fromUtf8("pb_avancement"))
        self.verticalLayout.addWidget(self.pb_avancement)

        self.retranslateUi(interface_analyse)
        QtCore.QMetaObject.connectSlotsByName(interface_analyse)

    def retranslateUi(self, interface_analyse):
        interface_analyse.setWindowTitle(_translate("interface_analyse", "Comparaison de données antérieures (t-1)", None))
        self.label.setText(_translate("interface_analyse", "Sélectionner la connexion à la base de données", None))
        self.pb_dbConnect.setText(_translate("interface_analyse", "Connecter", None))
        self.groupBox_2.setTitle(_translate("interface_analyse", "Destination", None))
        self.label_3.setText(_translate("interface_analyse", "Schéma destination", None))
        self.label_4.setText(_translate("interface_analyse", "Couche destination", None))
        self.groupBox_3.setTitle(_translate("interface_analyse", "Origine", None))
        self.label_6.setText(_translate("interface_analyse", "Schema MOS", None))
        self.label_13.setText(_translate("interface_analyse", "Couche MOS", None))
        self.label_2.setText(_translate("interface_analyse", "Année T-1", None))
        self.groupBox.setTitle(_translate("interface_analyse", "Données nécessaires", None))
        self.label_61.setText(_translate("interface_analyse", "FF pnb10_parcelle T0", None))
        self.groupBox_4.setTitle(_translate("interface_analyse", "Données facultatives", None))
        self.label_14.setText(_translate("interface_analyse", "edigeo batiment T-1", None))
        self.label_65.setText(_translate("interface_analyse", "ign  bati industrie T-1", None))
        self.label_66.setText(_translate("interface_analyse", "ign bati remarquable T-1", None))
        self.label_67.setText(_translate("interface_analyse", "ign bati indiferencie T-1", None))
        self.rb_geom.setText(_translate("interface_analyse", "geom", None))
        self.label_7.setText(_translate("interface_analyse", "Champ geom BD TOPO", None))
        self.rb_the_geom.setText(_translate("interface_analyse", "the_geom", None))
        self.pb_start.setText(_translate("interface_analyse", "Start", None))
        self.lbl_etape.setText(_translate("interface_analyse", "TextLabel", None))

