# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_evolgeom.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_interface_evolgeom(object):
    def setupUi(self, interface_evolgeom):
        interface_evolgeom.setObjectName(_fromUtf8("interface_evolgeom"))
        interface_evolgeom.resize(564, 627)
        interface_evolgeom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_evolgeom.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(interface_evolgeom)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(interface_evolgeom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtGui.QComboBox(interface_evolgeom)
        self.cb_connexion.setObjectName(_fromUtf8("cb_connexion"))
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtGui.QPushButton(interface_evolgeom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName(_fromUtf8("pb_dbConnect"))
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtGui.QGroupBox(interface_evolgeom)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtGui.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName(_fromUtf8("cb_schema_desti"))
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName(_fromUtf8("le_table_desti"))
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(interface_evolgeom)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cb_schema_origin = QtGui.QComboBox(self.groupBox_3)
        self.cb_schema_origin.setObjectName(_fromUtf8("cb_schema_origin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_schema_origin)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cb_table_origin = QtGui.QComboBox(self.groupBox_3)
        self.cb_table_origin.setObjectName(_fromUtf8("cb_table_origin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cb_table_origin)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(interface_evolgeom)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cb_schema_new = QtGui.QComboBox(self.groupBox_4)
        self.cb_schema_new.setObjectName(_fromUtf8("cb_schema_new"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_schema_new)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.cb_table_new = QtGui.QComboBox(self.groupBox_4)
        self.cb_table_new.setObjectName(_fromUtf8("cb_table_new"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cb_table_new)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.pb_start = QtGui.QPushButton(interface_evolgeom)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtGui.QLabel(interface_evolgeom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName(_fromUtf8("lbl_etape"))
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtGui.QProgressBar(interface_evolgeom)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName(_fromUtf8("pb_avancement"))
        self.verticalLayout.addWidget(self.pb_avancement)
        self.pb_start.raise_()
        self.pb_avancement.raise_()
        self.lbl_etape.raise_()
        self.pb_dbConnect.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()

        self.retranslateUi(interface_evolgeom)
        QtCore.QMetaObject.connectSlotsByName(interface_evolgeom)

    def retranslateUi(self, interface_evolgeom):
        interface_evolgeom.setWindowTitle(_translate("interface_evolgeom", "Mise à jour des géométries", None))
        self.label.setText(_translate("interface_evolgeom", "Sélectionner la connexion à la base de données", None))
        self.pb_dbConnect.setText(_translate("interface_evolgeom", "Connecter", None))
        self.groupBox_2.setTitle(_translate("interface_evolgeom", "Destination", None))
        self.label_3.setText(_translate("interface_evolgeom", "Schéma destination", None))
        self.label_4.setText(_translate("interface_evolgeom", "Couche destination", None))
        self.groupBox_3.setTitle(_translate("interface_evolgeom", "Origine", None))
        self.label_6.setText(_translate("interface_evolgeom", "Schema ", None))
        self.label_13.setText(_translate("interface_evolgeom", "Couche ", None))
        self.groupBox_4.setTitle(_translate("interface_evolgeom", "Nouvelles géométries", None))
        self.label_7.setText(_translate("interface_evolgeom", "Schema ", None))
        self.label_14.setText(_translate("interface_evolgeom", "Couche ", None))
        self.pb_start.setText(_translate("interface_evolgeom", "Start", None))
        self.lbl_etape.setText(_translate("interface_evolgeom", "TextLabel", None))

