# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_evolution.ui'
#
# Created: Thu Jan 31 14:03:25 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_interface_evolution(object):
    def setupUi(self, interface_evolution):
        interface_evolution.setObjectName(_fromUtf8("interface_evolution"))
        interface_evolution.resize(564, 627)
        interface_evolution.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_evolution.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(interface_evolution)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(interface_evolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtGui.QComboBox(interface_evolution)
        self.cb_connexion.setObjectName(_fromUtf8("cb_connexion"))
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtGui.QPushButton(interface_evolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName(_fromUtf8("pb_dbConnect"))
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtGui.QGroupBox(interface_evolution)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtGui.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName(_fromUtf8("cb_schema_desti"))
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName(_fromUtf8("le_table_desti"))
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(interface_evolution)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cb_schema = QtGui.QComboBox(self.groupBox_3)
        self.cb_schema.setObjectName(_fromUtf8("cb_schema"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_schema)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.cb_table = QtGui.QComboBox(self.groupBox_3)
        self.cb_table.setObjectName(_fromUtf8("cb_table"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cb_table)
        self.le_annee = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_annee.sizePolicy().hasHeightForWidth())
        self.le_annee.setSizePolicy(sizePolicy)
        self.le_annee.setObjectName(_fromUtf8("le_annee"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_annee)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(interface_evolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_61 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_61)
        self.cb_ff_parcelle = QtGui.QComboBox(self.groupBox)
        self.cb_ff_parcelle.setObjectName(_fromUtf8("cb_ff_parcelle"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cb_ff_parcelle)
        self.verticalLayout.addWidget(self.groupBox)
        self.pb_start = QtGui.QPushButton(interface_evolution)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtGui.QLabel(interface_evolution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName(_fromUtf8("lbl_etape"))
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtGui.QProgressBar(interface_evolution)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName(_fromUtf8("pb_avancement"))
        self.verticalLayout.addWidget(self.pb_avancement)

        self.retranslateUi(interface_evolution)
        QtCore.QMetaObject.connectSlotsByName(interface_evolution)

    def retranslateUi(self, interface_evolution):
        interface_evolution.setWindowTitle(_translate("interface_evolution", "Evolution des données ultérieur (t+1)", None))
        self.label.setText(_translate("interface_evolution", "Sélectionner la connexion à la base de données", None))
        self.pb_dbConnect.setText(_translate("interface_evolution", "Connecter", None))
        self.groupBox_2.setTitle(_translate("interface_evolution", "Destination", None))
        self.label_3.setText(_translate("interface_evolution", "Schéma destination", None))
        self.label_4.setText(_translate("interface_evolution", "Couche destination", None))
        self.groupBox_3.setTitle(_translate("interface_evolution", "Origine", None))
        self.label_6.setText(_translate("interface_evolution", "Schema MOS", None))
        self.label_13.setText(_translate("interface_evolution", "Couche MOS", None))
        self.label_2.setText(_translate("interface_evolution", "Année T+1", None))
        self.groupBox.setTitle(_translate("interface_evolution", "Données nécessaires", None))
        self.label_61.setText(_translate("interface_evolution", "FF pnb10_parcelle T0", None))
        self.pb_start.setText(_translate("interface_evolution", "Start", None))
        self.lbl_etape.setText(_translate("interface_evolution", "TextLabel", None))

