# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_evolgeom.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_interface_evolgeom(object):
    def setupUi(self, interface_evolgeom):
        interface_evolgeom.setObjectName("interface_evolgeom")
        interface_evolgeom.resize(505, 605)
        interface_evolgeom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_evolgeom.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(interface_evolgeom)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info = QtWidgets.QLabel(interface_evolgeom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info.sizePolicy().hasHeightForWidth())
        self.label_info.setSizePolicy(sizePolicy)
        self.label_info.setStyleSheet("background-color: rgb(255, 157, 157);")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(interface_evolgeom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtWidgets.QComboBox(interface_evolgeom)
        self.cb_connexion.setObjectName("cb_connexion")
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtWidgets.QPushButton(interface_evolgeom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName("pb_dbConnect")
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtWidgets.QGroupBox(interface_evolgeom)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName("cb_schema_desti")
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName("le_table_desti")
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(interface_evolgeom)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cb_schema_origin = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_schema_origin.setObjectName("cb_schema_origin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_schema_origin)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_table_origin = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_table_origin.setObjectName("cb_table_origin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_table_origin)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(interface_evolgeom)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_info_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info_2.sizePolicy().hasHeightForWidth())
        self.label_info_2.setSizePolicy(sizePolicy)
        self.label_info_2.setStyleSheet("background-color: rgb(189, 223, 255);")
        self.label_info_2.setObjectName("label_info_2")
        self.verticalLayout_5.addWidget(self.label_info_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cb_schema_new = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_schema_new.setObjectName("cb_schema_new")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_schema_new)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cb_table_new = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_table_new.setObjectName("cb_table_new")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_table_new)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.pb_start = QtWidgets.QPushButton(interface_evolgeom)
        self.pb_start.setObjectName("pb_start")
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtWidgets.QLabel(interface_evolgeom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName("lbl_etape")
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtWidgets.QProgressBar(interface_evolgeom)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName("pb_avancement")
        self.verticalLayout.addWidget(self.pb_avancement)
        self.pb_start.raise_()
        self.pb_avancement.raise_()
        self.lbl_etape.raise_()
        self.pb_dbConnect.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.label_info.raise_()

        self.retranslateUi(interface_evolgeom)
        QtCore.QMetaObject.connectSlotsByName(interface_evolgeom)

    def retranslateUi(self, interface_evolgeom):
        _translate = QtCore.QCoreApplication.translate
        interface_evolgeom.setWindowTitle(_translate("interface_evolgeom", "Mise à jour des géométries ultérieures (t+1)"))
        self.label_info.setText(_translate("interface_evolgeom", "Fonctionnalité en développement à ne pas utiliser en production."))
        self.label.setText(_translate("interface_evolgeom", "Sélectionner la connexion à la base de données"))
        self.pb_dbConnect.setText(_translate("interface_evolgeom", "Connecter"))
        self.groupBox_2.setTitle(_translate("interface_evolgeom", "Destination"))
        self.label_3.setText(_translate("interface_evolgeom", "Schéma destination"))
        self.label_4.setText(_translate("interface_evolgeom", "Couche destination"))
        self.groupBox_3.setTitle(_translate("interface_evolgeom", "Dernier MOS réalisé par PIAO"))
        self.label_6.setText(_translate("interface_evolgeom", "Schema "))
        self.label_13.setText(_translate("interface_evolgeom", "Couche "))
        self.groupBox_4.setTitle(_translate("interface_evolgeom", "Nouveau socle géométrique"))
        self.label_info_2.setText(_translate("interface_evolgeom", "La couche ne doit présenter aucun problème de topologie"))
        self.label_7.setText(_translate("interface_evolgeom", "Schema "))
        self.label_14.setText(_translate("interface_evolgeom", "Couche "))
        self.pb_start.setText(_translate("interface_evolgeom", "Start"))
        self.lbl_etape.setText(_translate("interface_evolgeom", "TextLabel"))

