# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_analyse.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_interface_analyse(object):
    def setupUi(self, interface_analyse):
        interface_analyse.setObjectName("interface_analyse")
        interface_analyse.resize(547, 710)
        interface_analyse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        interface_analyse.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(interface_analyse)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(interface_analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cb_connexion = QtWidgets.QComboBox(interface_analyse)
        self.cb_connexion.setObjectName("cb_connexion")
        self.horizontalLayout_2.addWidget(self.cb_connexion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_dbConnect = QtWidgets.QPushButton(interface_analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dbConnect.sizePolicy().hasHeightForWidth())
        self.pb_dbConnect.setSizePolicy(sizePolicy)
        self.pb_dbConnect.setObjectName("pb_dbConnect")
        self.verticalLayout.addWidget(self.pb_dbConnect)
        self.groupBox_2 = QtWidgets.QGroupBox(interface_analyse)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cb_schema_desti = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_schema_desti.setObjectName("cb_schema_desti")
        self.horizontalLayout.addWidget(self.cb_schema_desti)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.le_table_desti = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_table_desti.sizePolicy().hasHeightForWidth())
        self.le_table_desti.setSizePolicy(sizePolicy)
        self.le_table_desti.setObjectName("le_table_desti")
        self.horizontalLayout.addWidget(self.le_table_desti)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(interface_analyse)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cb_schema = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_schema.setObjectName("cb_schema")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_schema)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cb_table = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_table.setObjectName("cb_table")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_table)
        self.le_annee = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_annee.sizePolicy().hasHeightForWidth())
        self.le_annee.setSizePolicy(sizePolicy)
        self.le_annee.setObjectName("le_annee")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_annee)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(interface_analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_61 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.cb_ff_parcelle = QtWidgets.QComboBox(self.groupBox)
        self.cb_ff_parcelle.setObjectName("cb_ff_parcelle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_ff_parcelle)
        self.verticalLayout.addWidget(self.groupBox)
        self.scrollArea_2 = QtWidgets.QScrollArea(interface_analyse)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 514, 225))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 1, 1, 1)
        self.cb_geobati = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_geobati.setObjectName("cb_geobati")
        self.gridLayout_5.addWidget(self.cb_geobati, 1, 2, 1, 2)
        self.cb_indust = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_indust.setObjectName("cb_indust")
        self.gridLayout_5.addWidget(self.cb_indust, 3, 2, 1, 2)
        self.label_65 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setObjectName("label_65")
        self.gridLayout_5.addWidget(self.label_65, 3, 1, 1, 1)
        self.cb_batirem = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_batirem.setObjectName("cb_batirem")
        self.gridLayout_5.addWidget(self.cb_batirem, 4, 2, 1, 2)
        self.cb_bati_indif = QtWidgets.QComboBox(self.groupBox_4)
        self.cb_bati_indif.setObjectName("cb_bati_indif")
        self.gridLayout_5.addWidget(self.cb_bati_indif, 5, 2, 1, 2)
        self.label_66 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName("label_66")
        self.gridLayout_5.addWidget(self.label_66, 4, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setObjectName("label_67")
        self.gridLayout_5.addWidget(self.label_67, 5, 1, 1, 1)
        self.rb_geom = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_geom.setChecked(True)
        self.rb_geom.setObjectName("rb_geom")
        self.gridLayout_5.addWidget(self.rb_geom, 7, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 7, 1, 1, 1)
        self.rb_the_geom = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_the_geom.setObjectName("rb_the_geom")
        self.gridLayout_5.addWidget(self.rb_the_geom, 7, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.pb_start = QtWidgets.QPushButton(interface_analyse)
        self.pb_start.setObjectName("pb_start")
        self.verticalLayout.addWidget(self.pb_start)
        self.lbl_etape = QtWidgets.QLabel(interface_analyse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_etape.sizePolicy().hasHeightForWidth())
        self.lbl_etape.setSizePolicy(sizePolicy)
        self.lbl_etape.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_etape.setObjectName("lbl_etape")
        self.verticalLayout.addWidget(self.lbl_etape)
        self.pb_avancement = QtWidgets.QProgressBar(interface_analyse)
        self.pb_avancement.setProperty("value", 24)
        self.pb_avancement.setObjectName("pb_avancement")
        self.verticalLayout.addWidget(self.pb_avancement)
        self.pb_start.raise_()
        self.pb_avancement.raise_()
        self.lbl_etape.raise_()
        self.pb_dbConnect.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.scrollArea_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(interface_analyse)
        QtCore.QMetaObject.connectSlotsByName(interface_analyse)

    def retranslateUi(self, interface_analyse):
        _translate = QtCore.QCoreApplication.translate
        interface_analyse.setWindowTitle(_translate("interface_analyse", "Comparaison de données antérieures (t-1)"))
        self.label.setText(_translate("interface_analyse", "Sélectionner la connexion à la base de données"))
        self.pb_dbConnect.setText(_translate("interface_analyse", "Connecter"))
        self.groupBox_2.setTitle(_translate("interface_analyse", "Destination"))
        self.label_3.setText(_translate("interface_analyse", "Schéma destination"))
        self.label_4.setText(_translate("interface_analyse", "Couche destination"))
        self.groupBox_3.setTitle(_translate("interface_analyse", "Origine"))
        self.label_6.setText(_translate("interface_analyse", "Schema MOS"))
        self.label_13.setText(_translate("interface_analyse", "Couche MOS"))
        self.label_2.setText(_translate("interface_analyse", "Année T-1"))
        self.groupBox.setTitle(_translate("interface_analyse", "Données nécessaires"))
        self.label_61.setText(_translate("interface_analyse", "FF pnb10_parcelle T0"))
        self.groupBox_4.setTitle(_translate("interface_analyse", "Données facultatives"))
        self.label_14.setText(_translate("interface_analyse", "edigeo batiment T-1"))
        self.label_65.setText(_translate("interface_analyse", "ign  bati industrie T-1"))
        self.label_66.setText(_translate("interface_analyse", "ign bati remarquable T-1"))
        self.label_67.setText(_translate("interface_analyse", "ign bati indiferencie T-1"))
        self.rb_geom.setText(_translate("interface_analyse", "geom"))
        self.label_7.setText(_translate("interface_analyse", "Champ geom BD TOPO"))
        self.rb_the_geom.setText(_translate("interface_analyse", "the_geom"))
        self.pb_start.setText(_translate("interface_analyse", "Start"))
        self.lbl_etape.setText(_translate("interface_analyse", "TextLabel"))

